### ISSUE TITLE
Clang compatibility

### ISSUE THREAD

**Issue by jacobgelling** [lecram/gifdec#10]
gifdec errors on compile with Windows 10 using the latest clang on example.c.

Seemingly it's missing a library not stated in the readme:
![error2](https://user-images.githubusercontent.com/3254275/97600974-8c88d800-1a01-11eb-949c-0c372901d571.png)

The above all works fine on my Debian install but not Windows.

**Comment by lecram** [comment]
Hi @jacobgelling.

Looks like the C Runtime (CRT) library provided by Windows 10 is refusing to provide some basic POSIX functions like `open()` for some reason. I'm not familiar with this environment (Windows + clang) so I'll have to investigate this further.

There's some [interesting information from Microsoft about POSIX compatibility](https://docs.microsoft.com/en-us/cpp/c-runtime-library/compatibility?view=msvc-160), specifically this:

> The C++ standard reserves names that begin with an underscore in the global namespace to the implementation. Both the POSIX functions and Microsoft-specific runtime library functions are in the global namespace, but aren't part of the standard C runtime library. That's why the preferred Microsoft implementations of these functions have a leading underscore. For portability, the UCRT also supports the default names, but the Microsoft C++ compiler issues a deprecation warning when code that uses them is compiled. Only the default names are deprecated, not the functions themselves. To suppress the warning, define _CRT_NONSTDC_NO_WARNINGS before including any headers in code that uses the original POSIX names.

So that might explain the warnings but I'm still not sure about the linker errors. Maybe try adding a leading underscore to those functions (i.e. `_open()`, `_setmode()`, `_read()`, etc)?

**Comment by jacobgelling** [comment]
I got this working by using the Clang compiler provided with MSVC, rather than the binary from the LLVM website. I didn't have to add the underscore then. Thanks.
