### ISSUE TITLE
Halt in read_image_data after some frame 

### ISSUE THREAD

**Issue by kisvegabor** [lecram/gifdec#13]
Hi,

Thank you for this great library. We are using it in [LVGL](https://github.com/lvgl/lvgl/) as an external library. See [lv_lib_gif](https://github.com/lvgl/lv_lib_gif).

There we use a slightly modified version of your lib and noticed that it freezes with a gif.

I reproduced the issue with your original library too:
```c
  gd_GIF * g = gd_open_gif("./a.gif");

  uint8_t buf[1024 * 1024];

  for(int i = 0; i < 50; i++) {
      int ret = gd_get_frame(g);
      printf("i: %d, ret: %d\n", i);
      gd_render_frame(g, buf);
  }
```

The output is:
```
i: 0, ret: 0
i: 1, ret: 0
i: 2, ret: 0
i: 3, ret: 0
i: 4, ret: 0
i: 5, ret: 0
i: 6, ret: 0
i: 7, ret: 0
i: 8, ret: 0
i: 9, ret: 0
i: 10, ret: 0
i: 11, ret: 0
```

The debugger says it spins the `while(1)` of  `read_image_data`. 

We use this image:
![a](https://user-images.githubusercontent.com/7599318/115580215-2d789180-a2c7-11eb-8285-eff081023af1.gif)

Do you have any ideas about what could be the issue?

**Comment by lecram** [comment]
Hi @kisvegabor, thanks for reporting this bug.

I'm looking into the issue. This is what I've found so far:

The decompression table is getting corrupted possibly due to a malformed GIF. The freeze happens because there's a circular reference in the LZW table, which as far as I can tell shouldn't happen on valid input.
There's a comment embedded in the file saying "Resized on https://ezgif.com/resize". That site sometimes ["produces buggy results"](https://ezgif.com/help/flickering-gifs).
Re-encoding the file using some robust tool (e.g. `gifsicle a.gif -o a_ok.gif`) seems to remove the problem.
Just to be clear, I'm not proposing this as a solution but simply sharing some information on the issue; gifdec shouldn't freeze on any input, specially if other programs can read the same GIF.

One way to make gifdec less prone to this kind of issue is changing the *inner* `while (1)` in `read_image_data()` to this:

    for (i = 0; i < str_len; i++)
Circular references can also be detected in `add_entry()` by ensuring that `table->entries[prefix].length == length - 1`. But since other programs seem to show the complete animation correctly, there must be a way to handle this situation without completely discarding the frame.

I'll keep investigating this.

**Comment by kisvegabor** [comment]
Thank you very much for looking into it. 

I've used `ez-gif` to reconvert the file in the hope that it will solve the issue but it didn't. 
Thank you for pointing out the issues with ez-gif and ImageMagick. 

I wonder how my PC can play the gif it has circular reference. Do you have any ideas?

**Comment by lecram** [comment]
Turns out frame # 12 of this GIF doesn't have a "stop code" at the end of compressed data. gifdec relied on the presence of this sentinel to mark the end of LZW decompression. Without the sentinel, gifdec just kept trying to decompress image data beyond its limits, eventually reaching some invalid LZW data that caused the circular reference in the code table.

Fortunately there are two other ways to identify the end of the compressed data:
1. when we reach a sub-block with zero size (a.k.a. block terminator);
2. when we reach the total number of pixels expected (frame_width * frame_height).

So I changed gifdec to also check for any of the two conditions above before trying to decompress more pixels.

Now the GIF above doesn't freeze, because it contains proper block terminators. It also has the correct number of pixels in all frames.

Please update your version of gifdec and let me know if there's any issue.

**Comment by kisvegabor** [comment]
Works like a charm! :slightly_smiling_face: 
Thank you very much for fixing this!

Let me know if you will work with embedded UI and planning to use LVGL. I'd be glad to help! :wink:
