### ISSUE TITLE
GIF parses background problem

### ISSUE THREAD

**Issue by jianjunxia** [lecram/gifdec#21]
https://github.com/lecram/gifdec/blob/1dcbae19363597314f6623010cc80abad4e47f7c/gifdec.c#L109
i think this code has some bug, when background=#000000, please see this issues：
https://github.com/lvgl/lv_lib_gif/issues/38#issuecomment-10
![zoomies_test](https://user-images.githubusercontent.com/35299508/154444173-665110cf-1344-4911-a43b-a03006a8180e.gif)
42647439

**Comment by lecram** [comment]
> https://github.com/lecram/gifdec/blob/1dcbae19363597314f6623010cc80abad4e47f7c/gifdec.c#L109

The purpose of this line is avoiding redundant `memcpy()` calls, for performance. Since the frame buffer was allocated with `calloc()`, all pixels are already #000000.

In the LVGL GIF library, on the other hand, the frame buffer is allocated with `lv_mem_alloc()` which doesn't set the buffer contents to zero. That's why that line causes issues there.
