### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by fbeaulier** [lecram/gifdec#22]
Hi,
Great piece of software but can i use it in my project ?
You should tell people under what license this code is released.
Without any license i have no right to use your code !

See here:
https://choosealicense.com/

If you just don't care and want to let everyone just do whatever they want with it, i suggest you choose an MIT license.
Go here https://choosealicense.com/licenses/mit/ and copy / paste the license text in the header of each c and h file, that's all.
(This involves defining a copyright with your name)

Best regards

Francois

**Comment by fbeaulier** [comment]
Missed the last lines of the README

```
Copying
-------
All of the source code and documentation for gifdec is released into the
public domain and provided without warranty of any kind.
```

**Comment by lecram** [comment]
Hi @fbeaulier.

Lately I'm putting most of my stuff on public domain so that people can just copy, paste and adapt the code into any project without having to put my name on it. If the code is any good, just steal it. I don't care about "Intellectual property".

Here's some info about the legal status of public domain: https://cr.yp.to/publicdomain.html
